services:
  - type: web
    name: saber-pro-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.dashboard.app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PYTHONPATH
        value: .
    healthCheckPath: /
    autoDeploy: true
